User.create! :name => 'Matt', :email => 'matthewtownsen@gmail.com', :password => 'junior38', :password_confirmation => 'junior38'
User.create! :name => 'Heather', :email => 'hnsmith1984@gmail.com', :password => 'amber2002', :password_confirmation => 'amber2002'
Category.create! :name => 'I feel loved and cared for when you...'
Category.create! :name => 'I use to feel loved and cared for when you...'
Category.create! :name => 'I want you to...'
